server:
  port: ${APP_SERVICE_PORT:8080}

logging:
  level:
    root: ${APP_SERVICE_ROOT_LOG_LEVEL:INFO}
    org.springframework: ${APP_SERVICE_SPRING_LOG_LEVEL:INFO}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APP_SERVICE_NAME:app-telegram-administrative-proceedings-service}
  jpa:
    # enable logging of SQL statements.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: ${APP_SERVICE_MONGODB_URI:uri}
      database: ${APP_SERVICE_MONGODB_DATABASE:app-telegram-rss-service-db}
      auto-index-creation: true

telegram:
  bot:
    username: ${APP_SERVICE_TELEGRAM_BOT_USERNAME:bot_name}
    token: ${APP_SERVICE_TELEGRAM_BOT_TOKEN:app_token}

management:
  endpoints:
    web:
      exposure:
        include:
          - health

scheduled:
  processing:
    crone: ${APP_SERVICE_SCHEDULER_PROCESSING_CRONE:0 */1 * * * *}